# Generated by Django 5.1.1 on 2024-09-28 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_rename_book_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='author',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='genre',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
